### ISSUE TITLE
Support ARM arch

### ISSUE THREAD

**Issue by JorTurFer** [kedacore/sample-go-rabbitmq#33]
Nowadays is common the scenario when users have an ARM machine with Mac M1. KEDA supports ARM64 but this example is build with non ARM64 images, so basically those users cannot test and play with KEDA locally. It'd be nice if we added the needed changes to make this demo runnable on ARM64

**Comment by rodrigoechaide** [comment]
@JorTurFer I can work on this issue.

**Comment by jeffhollan** [comment]
Sorry @rodrigoechaide didn't notice you also flagged you'd help with this. Saw someone on slack asking for this. I pushed a version of the container to GitHub registries and linked to this repo - should support both `linux/arm64` and `linux/amd64` archs. Feel free to check out PR if you didn't already start on this

**Comment by rodrigoechaide** [comment]
@jeffhollan Great! I will check the PR. The only thing I made was working on is the update of the README to use the official Rabbit Image. I can make a PR with that change.

**Comment by jeffhollan** [comment]
That would be awesome. Was trying to find out the best way to get rabbitmq in the cluster last night on my M1 but didn't find a helm chart to do it - not sure if thinking is we create our own deploy.YAML to just use the rabbitmq image directly but would love some help there.

**Comment by rodrigoechaide** [comment]
@jeffhollan What I did was to use the bitnami helm chart and modify the image to the rabbit official image that does support ARM. At least with that change rabbitmq was up and running but I couldn't go further with the demo because the rabbitmq-consumer was failing because of the lack of support of ARM. I will continue testing the full demo now that you introduced the changes to support ARM ❤️.
